name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      APPLICATION_ADS_ID: ${{ secrets.APPLICATION_ADS_ID }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Add the secret to the manifest file
      uses: MathieuSoysal/replace-string-in-file@v1.0.0
      with:
        file: AndroidManifest.xml
        old-string: @string/application_ad_id
        new-string: ${{ env.APPLICATION_ADS_ID }}
        
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
