name: Android CI

on:
  push:
    branches: [ "master", "workflow_test", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Add the secret to the manifest file
      run: |
          sed -i "s|@string/application_ad_id|${{ secrets.APPLICATION_ADS_ID }}|g" app/src/main/AndroidManifest.xml

    - name: Replace references with secrets
      uses: jannekem/run-python-script-action@v1
      with:
        script: |
          file = "app/src/main/java/com/tetsoft/typego/game/presentation/TimeGameViewModel.kt"#"sample.txt
          import_reference = "import com.tetsoft.typego.Config"
          api_reference = "Config.INTERSTITIAL_ID"
          secret = "${{ secrets.INTERSTITIAL_ADS_ID }}"

          with open(file, 'r') as file_read:
              lines = file_read.readlines()

          with open(file, 'w') as file_write:
              for line in lines:
                  if(line.__contains__(api_reference) == True):
                      file_write.write(line.replace(api_reference, "\""+secret+"\""))
                      print("Replaced api key")
                  elif (line.__contains__(import_reference) == False):
                      file_write.write(line)
        
    - name: set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
