name: Android CI

on:
  push:
    branches: [ "master", "workflow_test", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Add the secret to the manifest file
      run: |
          sed -i "s|@string/application_ad_id|${{ secrets.APPLICATION_ADS_ID }}|g" app/src/main/AndroidManifest.xml

    - name: Add the secret for the interstitial ads
      shell: bash
      run: |
        secret_value="${{ secrets.INTERSTITIAL_ADS_ID }}"
        escaped_secret_value=$(printf '%s\n' "$secret_value" | sed -e 's/[]\/$*.^[]/\\&/g')
        sed -i "s|com.tetsoft.typego.Config.INTERSTITIAL_ID|\"$escaped_secret_value\"|g" app/src/main/java/com/tetsoft/typego/ui/fragment/game/GameOnTimeViewModel.kt
        
    - name: set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
