name: Android CI

on:
  push:
    branches: [ "master", "workflow_test" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      APPLICATION_ADS_ID: ${{ secrets.APPLICATION_ADS_ID }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Add the secret to the manifest file
      run: |
          sed -i "s|@string/application_ad_id|${{ secrets.APPLICATION_ADS_ID }}|g" app/src/main/AndroidManifest.xml
        
    - name: set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        gradle-version: '8.2.0-alpha16'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
