name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Add the secret to the manifest file
      run: |
          sed -i "s|@string/application_ad_id|${{ secrets.APPLICATION_ADS_ID }}|g" app/src/main/AndroidManifest.xml

    - name: Add the secret for the interstitial ads
      uses: MathieuSoysal/replace-string-in-file@v1.0.0
      with:
        file: app/src/main/java/com/tetsoft/typego/ui/fragment/game/GameOnTimeViewModel.kt
        old-string: 'com.tetsoft.typego.Config.INTERSTITIAL_ID'
        new-string: \"${{ secrets.INTERSTITIAL_ADS_ID }}\"
        
    - name: set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
